runtime: java
env: flex
runtime_config:
  service: gcp-cloud-project
  operating_system: ubuntu22
  runtime_version: 17
handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1